[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "formative"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "statsmodels",
    "pandas",
]

[dependency-groups]
dev = ["pytest", "pytest-cov"]
